### ISSUE TITLE
Command line tutorial

### ISSUE THREAD

**Issue by RabeaGleissner** [Harri24/apprenticeship#1]
follow this tutorial https://learnrubythehardway.org/book/appendixa.html

**Comment by Harri24** [comment]
This was the tits - great way to get into the command line which I was both embarrassed I hadn't even really been aware of before and excited to get to stuck into - I later found some additional resources to help test myself on the various commands which I will try and relocate! Another great thing about this is that it encourages the learner to write lots down in a notebook - a technique I use anyway (love a good pen and paper), but the prompt really encouraged me to think of additional ways (that may be more traditional) to boost learning - note cards for example.

**Comment by Harri24** [comment]
Also - on Monday I was lucky enough to sit with George for a bit in the afternoon while he was working in the command line / pulling and pushing stuff to github - this was great as it put some context to what I was learning and gave me a boost of confidence as I recognised the commands he writing. While this was a total coincidence, i think it was a massively beneficial addition to the course - putting these lessons in a Tes context
