### ISSUE TITLE
freeCodeCamp: Basic JavaScript

### ISSUE THREAD

**Issue by RabeaGleissner** [Harri24/apprenticeship#11]

**Comment by Harri24** [comment]
ooooo the dreaded javascript - getting through this was a laborious process, and took me a lot longer than anticipated. Yet, it was still good - though while I loved the freecodecamp lessons for HTML and CSS, this one didn't benefit quite a much from the v basic, stripped down approach. I found myself googling queries a lot more and finding alternate resources like this https://www.codecademy.com/learn/introduction-to-javascript . Though like the lessons for CSS and HTML it provides a good skeletal resource for me to refer back to when I am having issues.
