### ISSUE TITLE
Run engineering guide locally and raise a PR on it

### ISSUE THREAD

**Issue by RabeaGleissner** [Harri24/apprenticeship#17]
Instead of going to Github and editing there, clone the code to your laptop, run it locally, make changes, commit them and raise a PR.

**Comment by Harri24** [comment]
I know Heather showed me how to do this, but I am dim and I forgot some of the finer details - I actually have a task from Marco that requires me to do this, so if someone wouldn't mind just talking me through a bit of it (I've tried doing a couple of times - generally successful, but these were just for mucking around, and now I've got a more formal task I wouldn't mind some assistance......)
Thanks!!!!!
