### ISSUE TITLE
Hangman game: layout and styling (desktop view)

### ISSUE THREAD

**Issue by RabeaGleissner** [Harri24/apprenticeship#21]
The idea is that once you know JS, you can create the actual game logic. But for now, just do the layout and styling with HTML and CSS.
Basically, make the page look like the picture. 
Make git commits along the way and push the code to Github.

Here are some specs:
Colours used:
- Button: darkblue
- Button font colour: white
- Navigation: pink
- Main background: lightblue
- Main font: black
- Fonts used from GoogleFonts: 
- Comfortaa
= Inconsolata (just for secret word)
Mobile design for screen width smaller than 500px (font size is smaller, no pink border) Desktop design for screen width larger than 500px (font size is larger, with pink border)
Please create hover effect for links and button (be creative! Any hover effect is fine)

![hangman-desktop.png](https://images.zenhubusercontent.com/5bb2371e225f161e775f21d9/394cc279-6ec5-4a9b-ad46-28e7bd7e03a9)

**Comment by Harri24** [comment]
Loved working on this so great - will continue to edit it and tidy up my CSS, would love if someone could look over some of it with me, overall a great task.
